name: finch
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# app
# - birdhouse-eggshell
# xclim
#- xclim
- netcdf4
- numpy
- dask
- xarray
- scipy
- pip:
  - -e git+https://github.com/Ouranosinc/xclim.git#egg=xclim
