name: finch
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
# - pywps>=4.2
- pip
- jinja2
- click
- psutil
- bottleneck
# - xclim
- netcdf4
- numpy
- unidecode
- dask
# - xarray
- scipy
- pandas
- sentry-sdk
- pip:
  - -e git+https://github.com/geopython/pywps.git#egg=pywps
  - -e git+https://github.com/pydata/xarray.git#egg=xarray
  - -e git+https://github.com/Ouranosinc/xclim.git#egg=xclim
