name: finch
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
# - pywps>=4.2
- jinja2
- click
- psutil
- bottleneck
# - xclim
- netcdf4
- numpy
- unidecode
- dask
- xarray>=0.12
- scipy
- pip:
  - -e git+https://github.com/geopython/pywps.git#egg=pywps
  - -e git+https://github.com/Ouranosinc/xclim.git#egg=xclim
