name: finch
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- python=3.6
# - pywps>=4.2
- pip
- jinja2
- click
- psutil
- bottleneck
# - xclim
- netcdf4
- numpy
- unidecode
- dask
- xarray>=0.12
- scipy
- sentry-sdk
- siphon
- pip:
  - git+https://github.com/geopython/pywps.git#egg=pywps
  - git+https://github.com/Ouranosinc/xclim.git@8438b0e5001c4014d0a318b974863e2b4dc4cc41#egg=xclim
